import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Slab } from 'next/font/google';

const josefin = Josefin_Slab({
  subsets: ['latin'],
  variable: '--font-josefin', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.variable} font-serif min-h-screen flex`}
      >
        {children}
      </body>
    </html>
  );
}
